name : my_first action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Run a script
      env :
        HI : hello!
        WO : world!
      run : |
       echo $HI $WO
    - name : Run python program
      run : |
        python homework.py
 
 
      
