name : my_first action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Run a script
      env :
        hi : hello!
        world : world!
      run : echo &hi &world
    - name : Run python program
      run : python homework.py
 
 
      
