name : my_first action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Install python
      uses : actions/setup-python@v2
      with : 
        python-version: '3.x'
    - uses : actions/checkout@v2
    - name : Test python program
      run : |
        python homework.py
    
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo script
        env :
          HI : hello!
          WO : world!
          run : echo $HI $WO
   
    
    
 
 
      
